# Generated by Django 4.2.24 on 2025-10-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contacto_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=50)),
                ('emailCliente', models.EmailField(max_length=50)),
                ('nTelefonoCliente', models.CharField(max_length=15)),
                ('fechaCliente', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nTelefono',
            field=models.CharField(max_length=15),
        ),
    ]
