# Generated by Django 4.2.24 on 2025-10-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cliente_alter_contacto_ntelefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailSub', models.EmailField(max_length=50)),
                ('fechaSub', models.DateField(auto_now_add=True)),
                ('estadoSub', models.BooleanField(default=True)),
            ],
        ),
    ]
