# Generated by Django 4.2.24 on 2025-10-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscripcion',
            name='emailSub',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
