# Generated by Django 4.2.24 on 2025-10-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_subscripcion_emailsub'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscripcion',
            new_name='Suscripcion',
        ),
        migrations.RenameField(
            model_name='suscripcion',
            old_name='emailSub',
            new_name='emailSus',
        ),
        migrations.RenameField(
            model_name='suscripcion',
            old_name='estadoSub',
            new_name='estadoSus',
        ),
        migrations.RenameField(
            model_name='suscripcion',
            old_name='fechaSub',
            new_name='fechaSus',
        ),
    ]
