# Generated by Django 4.2.24 on 2025-10-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('thumb', models.ImageField(upload_to='')),
                ('descripcion', models.TextField()),
                ('nHabitaciones', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '10+')], default=1)),
                ('nBanos', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '10+')], default=1)),
                ('superficie', models.FloatField()),
                ('superficieConstruida', models.FloatField()),
                ('ubicacion', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=10)),
                ('moneda', models.CharField(choices=[('UF', 'UF'), ('CLP', '$')], default='CLP', max_length=3)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('conserje', models.BooleanField(default=False)),
                ('logia', models.BooleanField(default=False)),
                ('amoblado', models.BooleanField(default=False)),
                ('estacionamiento', models.BooleanField(default=False)),
                ('nEstacionamientos', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '10+')], default=1)),
                ('piscina', models.BooleanField(default=False)),
            ],
        ),
    ]
