# Generated by Django 4.2.24 on 2025-10-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('thumb', models.ImageField(upload_to='')),
                ('carrusel', models.ImageField(upload_to='')),
                ('nBanos', models.IntegerField()),
                ('nHabitaciones', models.IntegerField()),
                ('superficie', models.FloatField()),
                ('ubicacion', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
