# Generated by Django 4.2.24 on 2025-10-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, null=True),
        ),
    ]
