# Generated by Django 4.2.24 on 2025-10-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_propiedad_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
