# Generated by Django 4.2.24 on 2025-10-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_propiedad_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='nEstacionamientos',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '10+')], default=0),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='superficie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='superficieConstruida',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
