# Generated by Django 4.2.24 on 2025-10-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_propiedad_nestacionamientos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='nEstacionamientos',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '10+')], default=0),
        ),
    ]
