# Generated by Django 4.2.24 on 2025-10-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_propiedad_nestacionamientos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosPropiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperacionesPropiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiposPropiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPropiedad', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
